---
abstract: 'Moose Types for Vehicles (NHSTA 17 char VIN)'
author:
  - 'Evan Carroll, C<< <me at evancarroll.com> >>'
  - 'Evan Carroll <me@evancarroll.com>'
build_requires:
  ExtUtils::MakeMaker: 6.36
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: MooseX-Types-Vehicle
no_index:
  directory:
    - inc
    - t
requires:
  Moose: 2.06
  MooseX::Types: 0.35
  MooseX::Types::Moose: 0.35
resources:
  homepage: https://github.com/EvanCarroll/mx-t-vehicle
  license: http://dev.perl.org/licenses/
  repository: git://github.com/EvanCarroll/mx-t-vehicle.git
version: 0.02
